### PR TITLE
improve handling of unbound variables and refactor code

### PR DESCRIPTION
**Pull request by jaw111**
* add test if result binding has value for the variable
* refactor code for constructing display values to use switch statement and template literals for better code readability

### CODE REVIEW

**Comment by namedgraph** [comment]
Looks good, but maybe it should skip the table cell altogether if the value is not bound? By setting `td/@colspan`.

**Comment by jaw111** [comment]
I think colspan would be tricky as too many corner cases to handle.

I guess the question is what fits best from semantic html perspective for an unbound value. I suggest to take the lead from CSV and TSV serializations and just add an empty td element. I think the rest can be handled in CSS.

Let me try it out and, if it works, I'll update the pull request.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
From: Martynas Jusevičius ***@***.***>
Date: 21/04/2023 23:26 (GMT+01:00)
To: AtomGraph/SPARQL-Playground ***@***.***>
Cc: John Walker ***@***.***>, Author ***@***.***>
Subject: Re: [AtomGraph/SPARQL-Playground] improve handling of unbound variables and refactor code (PR #3)


Looks good, but maybe it should skip the table cell altogether if the value is not bound? By setting ***@***.***

**Comment by namedgraph** [comment]
Yeah empty `<td>` would be fine. Just remove the `"-"` for unbound then :)

**Comment by jaw111** [comment]
@namedgraph I've reworked a bit and set the [`empty-cells`](https://developer.mozilla.org/en-US/docs/Web/CSS/empty-cells) property on the results table to `hide` so the borders are not shown around those cells (also requires [`border-collapse`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-collapse) property is `separate`). It's quite subtle, but does give the user a visual cue that those variables are unbound.

**Review by namedgraph — APPROVED** [review]

**Comment by namedgraph** [comment]
Deployed now

**Pull request merged**
